version: '3.0'

scanning-settings:
  max-depth: 6
  exclude: []
  include-files: []
  system:
    targets: []


report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      vulnerabilities:
        67599:
            reason: Only applies if using private package repo.
            expires: '2026-04-17'
        64459:
            reason: No Known fix.
            expires: '2025-12-12'
        64396:
            reason: No Known fix.
            expires: '2025-12-12'
        70716:
            reason: No Known fix.
            expires: '2025-12-12'
        70715:
            reason: No Known fix.
            expires: '2025-12-12'


fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - high
        - medium
      exploitability:
        - critical
        - high
        - medium

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch
