[tool.poetry]
name = "fastapimsal"
version = "0.6.0"
description = "Library to authenticate users using MSAL"
authors = ["Oscar Giles <ogiles@turing.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.10"
anyio = "^4.4.0"
async_lru = "^1.0.2"
fastapi = "^0.115.6"
httpx = "^0.23"
itsdangerous = "^1.1.0"
msal = "^1.31.1"
pydantic = "^2.7.1"
pydantic-settings = "^2.3.4"
python-jose = {extras = ["cryptography"], version = "^3.2.0"}
uvicorn = {version = "^0.30.1", extras = ["standard"]}


[tool.poetry.group.dev.dependencies]
python-jose = "^3.3.0"
uvicorn = {version = "^0.17.6", extras = ["standard"]}
pre-commit = "^4.0.1"
safety = "^3.2.14"

[tool.poetry.group.dev.dependencies]
flake8 = "^5"
httpie-jwt-auth = "^0.4.0"
>>>>>>> 50d95e2 (update deps)
httpie = "3.2.1"  # addded to fix version to avoid SSL certificate vulnerability in 3.2.2
httpie-jwt-auth = "^0.4.0"
isort = "^5.8.0"
mypy = "^1.1.1"
pytest = "^7.2"
pylint = "^2.7.2"
safety = "^3.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"
