---

name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


###############
# Set the Job #
###############
jobs:

  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:

      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ################
      # Setup Python #
      ################
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Bootstrap poetry
        shell: bash
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Configure poetry
        shell: bash
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m poetry install

      - name: Run tests
        shell: bash
        env: # Or as an environment variable
          client_id: '00000000-0000-0000-0000-000000000000'
          tenant_id: '00000000-0000-0000-0000-000000000001'
          client_secret: 'imaabadasecret'
          session_secret: 'imaabadasecret'
          session_expire_time_minutes: '5'
        run: poetry run pytest
